#########################Automated tests trace#########################

self = <Tests.InitialPopulation.RelatedEntityCounts.test_aggregate_counts.TestAggregatedEntityCounts instance at 0x03ECFC88>
entity_with_related_counts = <PyTest.InputTestCriteria.InputTestCriteria.EntityWithField object at 0x0364A150>
search_api = <Search.Implementation.Contract.search.SearchAPI object at 0x035683B0>

    @pytest.mark.xre_demo
    def test_related_entity_count(self, entity_with_related_counts, search_api):
        entity_name = entity_with_related_counts.entity_type
        fieldname = entity_with_related_counts.field_name
        field_metadata = entity_with_related_counts.field_metadata
    
        genericentity = EntityBase(
            entity_name=entity_name
        )
        genericentity.authorization_token = self.authorization_token
        genericentity.base_url = self.env_config.get_path("MEGS", "url")
    
        self.search_api.entity_name = entity_name
        #self.search_api = SearchAPI(self.env_config,entity_name)
        #self.search_api.set_authorization_token(self.authorization_token)
    
        custom_query = self.add_custom_query(field_metadata["DisplayName"])
        (entity_id, target_entity_id) = self.es_client.get_entity_with_related_entities(
            firstclass=entity_name,
            secondclass=field_metadata["TargetEntityName"],
            custom_query=custom_query
        )
        self.logger.info("Found test data in Elastic Search. Test entity -{0} = {1}-, target entity -{2} = {3}-".format(
             entity_name,
             entity_id,
             field_metadata["TargetEntityName"],
             target_entity_id
        ))
    
        #Get entity details and check count
        get_req_code, get_req_text = genericentity.get_entity(
            params={
                "id": entity_id,
                "request_params": "relationCalculationTimeout=-1"
            }
        )
        target_entity_count = json.loads(get_req_text)[fieldname]
        self.logger.info("Target entity count in main entity details: {0}={1}".format(
            fieldname,
            target_entity_count
        ))
    
        #Get entity related entities and check count
        action_type = field_metadata["DisplayName"]
        if action_type in ["Annotations", "Attachments"]:
            action_type = "Notes"
        elif action_type in ["OpenActivities", "Histories"]:
            action_type = "Activities"
    
        get_req_code_1, get_req_text_1 = genericentity.get_entity(
            params={
                "id": entity_id,
                "action": action_type
            }
        )
        related_total_count = 0
        if custom_query:
            query_field = list(custom_query["query"]._values)[-1]
            query_values = []
            query_values.append(
                str(custom_query["query"]._values[list(custom_query["query"]._values)[-1]]).lower()
            )
            for item in json.loads(get_req_text_1)["Objects"]:
                if custom_query["occur_type"] in ["must", "should"]:
                    if str(item[query_field]).lower() in query_values:
                        related_total_count += 1
                else:
                    if str(item[query_field]).lower() not in query_values:
                        related_total_count += 1
        else:
            related_total_count = json.loads(get_req_text_1)["MetaData"]["Total"]
    
        self.logger.info("Get related entity counts completed.  MetaData.Total={0}".format(
            related_total_count
        ))
    
>       assert target_entity_count == related_total_count, "Get related entity counts not match to aggregate count in entity details"
E       AssertionError: Get related entity counts not match to aggregate count in entity details

C:\EdgeDeployment\FunctionalTests\src\Elasticsearch\Tests\InitialPopulation\RelatedEntityCounts\test_aggregate_counts.py:267: AssertionError
-------------------------------- Captured log ---------------------------------
requests_api.py             76 INFO     Sending HTTP request...
requests_api.py             83 DEBUG    Method type: GET
requests_api.py             94 DEBUG    Url: http://localhost/xre2113qa.nightly/api/authentication
requests_api.py             95 DEBUG    Headers: {'Authorization-Token': u'e1a18037a60f4528be3edb07f07f316d', 'Accept-Language': 'en-US,en;q=0.8', 'Content-Type': 'application/json', 'Accept-Encoding': 'deflate, gzip'}
connectionpool.py          176 INFO     Starting new HTTP connection (1): localhost
connectionpool.py          344 DEBUG    "GET /xre2113qa.nightly/api/authentication HTTP/1.1" 200 2124
requests_api.py            140 INFO     Response recieved...
requests_api.py            141 INFO     Response status: 200
requests_api.py            142 INFO     Response reason: OK
requests_api.py            143 INFO     Response time: 0:00:01.278000
connectionpool.py          296 DEBUG    "GET /xre2113qa.nightly.settings/ValueWithVersion%601/activitypointer HTTP/1.1" 200 9299
connectionpool.py          296 DEBUG    "GET /xre2113qa.nightly/_search HTTP/1.1" 200 1234
connectionpool.py          296 DEBUG    "GET /xre2113qa.nightly/_search HTTP/1.1" 200 3221
test_aggregate_counts.py   217 INFO     Found test data in Elastic Search. Test entity -opportunity = e971acbf-c777-e311-8d25-00155d280475-, target entity -activitypointer = 5ff2dad4-db8d-e311-a5b4-00155d28de35-
EntityBase.py              132 INFO     Sending GET request..
requests_api.py             76 INFO     Sending HTTP request...
requests_api.py             83 DEBUG    Method type: GET
requests_api.py             94 DEBUG    Url: http://localhost/xre2113qa.nightly/api/opportunity/e971acbf-c777-e311-8d25-00155d280475/
requests_api.py             95 DEBUG    Headers: {'Authorization-Token': u'e1a18037a60f4528be3edb07f07f316d', 'Accept-Language': 'en-US,en;q=0.8', 'Content-Type': 'application/json', 'Accept-Encoding': 'deflate, gzip'}
requests_api.py            127 DEBUG    Request params: relationCalculationTimeout=-1
connectionpool.py          176 INFO     Starting new HTTP connection (1): localhost
connectionpool.py          344 DEBUG    "GET /xre2113qa.nightly/api/opportunity/e971acbf-c777-e311-8d25-00155d280475/?relationCalculationTimeout=-1 HTTP/1.1" 200 3887
requests_api.py            140 INFO     Response recieved...
requests_api.py            141 INFO     Response status: 200
requests_api.py            142 INFO     Response reason: OK
requests_api.py            143 INFO     Response time: 0:00:03.048000
test_aggregate_counts.py   230 INFO     Target entity count in main entity details: related_activity=4
EntityBase.py              132 INFO     Sending GET request..
requests_api.py             76 INFO     Sending HTTP request...
requests_api.py             83 DEBUG    Method type: GET
requests_api.py             94 DEBUG    Url: http://localhost/xre2113qa.nightly/api/opportunity/e971acbf-c777-e311-8d25-00155d280475/Activities
requests_api.py             95 DEBUG    Headers: {'Authorization-Token': u'e1a18037a60f4528be3edb07f07f316d', 'Accept-Language': 'en-US,en;q=0.8', 'Content-Type': 'application/json', 'Accept-Encoding': 'deflate, gzip'}
connectionpool.py          176 INFO     Starting new HTTP connection (1): localhost
connectionpool.py          344 DEBUG    "GET /xre2113qa.nightly/api/opportunity/e971acbf-c777-e311-8d25-00155d280475/Activities HTTP/1.1" 200 8613
requests_api.py            140 INFO     Response recieved...
requests_api.py            141 INFO     Response status: 200
requests_api.py            142 INFO     Response reason: OK
requests_api.py            143 INFO     Response time: 0:00:00.900000
test_aggregate_counts.py   264 INFO     Get related entity counts completed.  MetaData.Total=3
#########################Server error trace#########################
{"index":[],"megs":[{"TimeStamp":"2014-02-18T08:55:14.4445454Z","Message":"Could not get the value of required parameter 'crm_account_id'","ErrorLevel":"WARN","Longdate":"2014-02-18 02:55:10.9760","ThreadId":"11 ","Logger":"AscendixRE.InsideView.Implementation.Requests.InsideViewRequestUtils","Exception":""},{"TimeStamp":"2014-02-18T08:55:14.5617254Z","Message":"Could not get the value of required parameter 'crm_account_id'","ErrorLevel":"WARN","Longdate":"2014-02-18 02:55:11.1488","ThreadId":"98 ","Logger":"AscendixRE.InsideView.Implementation.Requests.InsideViewRequestUtils","Exception":""},{"TimeStamp":"2014-02-18T08:55:14.6867174Z","Message":"Could not get the value of required parameter 'crm_account_id'","ErrorLevel":"WARN","Longdate":"2014-02-18 02:55:12.8928","ThreadId":"82 ","Logger":"AscendixRE.InsideView.Implementation.Requests.InsideViewRequestUtils","Exception":""}]}
