#########################Automated tests trace#########################

self = <MEGS.Tests.CRUD.test_entity_crud_action.TestEntityBase object at 0x03371250>
generic_entity_test_criteria = <PyTest.InputTestCriteria.InputTestCriteria.GenericEntityTestCriteria object at 0x034635F0>
search_api = <Search.Implementation.Contract.search.SearchAPI object at 0x033715F0>

    @pytest.mark.crud
    def test_update_entity(self, generic_entity_test_criteria, search_api):
        if isinstance(generic_entity_test_criteria, GenericEntityTestCriteria):
            entity = generic_entity_test_criteria.api_object
            entity.es_client = self.es_client
            _primary_key = self.es_client.edge_metadata[entity.entity_name].get_entity_primary_key_field()
    
            if not self.get_from_local_entity_storage(entity.entity_name):
                #Create entity
                create_response = list(entity.create_entity(params={}))
    
                #Check whether request has been performed successfully
                self.assertHttpResponseCode(create_response)
    
                #Create models
                create_resp_model = self.create_entity_model(search_api, create_response[1], _primary_key)
            else:
                create_resp_model = self.get_from_local_entity_storage(entity.entity_name)["data_model"]
    
            #Check whether entity instance present in index
            self.assertEntityInIndex(
                search_api,
                create_resp_model.logicalname,
                create_resp_model.id,
                primary_key_field=_primary_key
            )
    
            #Update entity
            update_response = list(entity.update_entity(params={"id": create_resp_model.id}))
    
            try:
                #Check whether request has been performed successfully
                self.assertHttpResponseCode(update_response, expected_resp_code=[200, 304])
    
                self.assertGenericEntityIncrementalUpdate(
                    create_resp_model,
                    entity.request_body_session[-1],
                    update_response,
                    search_api,
                    self.es_client,
                    _primary_key
                )
            except AssertionError, e:
>               pytest.fail("The entity has not been updated. Inner assertion: {0}".format(e.message))
E               Failed: The entity has not been updated. Inner assertion: Found data differencies between 2 objects  - {u'subject': (u'TEST Russian / \xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9', u'TEST French / Fran\xc3\xa7ais')}

C:\EdgeDeployment\FunctionalTests\src\MEGS\Tests\CRUD\test_entity_crud_action.py:120: Failed
-------------------------------- Captured log ---------------------------------
requests_api.py             76 INFO     Sending HTTP request...
requests_api.py             83 DEBUG    Method type: GET
requests_api.py             94 DEBUG    Url: http://localhost/xre2113qa.nightly/api/authentication
requests_api.py             95 DEBUG    Headers: {'Authorization-Token': u'6569219054d540fb97925f7d0b93ffb3', 'Accept-Language': 'en-US,en;q=0.8', 'Content-Type': 'application/json', 'Accept-Encoding': 'deflate, gzip'}
connectionpool.py          176 INFO     Starting new HTTP connection (1): localhost
connectionpool.py          344 DEBUG    "GET /xre2113qa.nightly/api/authentication HTTP/1.1" 200 2097
requests_api.py            140 INFO     Response recieved...
requests_api.py            141 INFO     Response status: 200
requests_api.py            142 INFO     Response reason: OK
requests_api.py            143 INFO     Response time: 0:00:00.476000
IncrementalUpdateAssertMixin.py   71 DEBUG    #######################
IncrementalUpdateAssertMixin.py   72 DEBUG    Search annotation in Index with Id - 88ecfe4b-7798-e311-aa29-00155d28de35 -
requests_api.py             76 INFO     Sending HTTP request...
requests_api.py             83 DEBUG    Method type: POST
requests_api.py             94 DEBUG    Url: http://localhost/xre2113qa.nightly/api/search/annotation
requests_api.py             95 DEBUG    Headers: {'Authorization-Token': u'6569219054d540fb97925f7d0b93ffb3', 'Accept-Language': 'en-US,en;q=0.8', 'Content-Type': 'application/json', 'Accept-Encoding': 'deflate, gzip'}
requests_api.py            104 DEBUG    Request body: {"ResultsFormat": null, "From": 0, "SelectedDateTimeFacets": null, "Relations": [], "PinTo": {"lat": -27.47018, "lon": 153.02911}, "NumericFacetFilters": [], "OrderBy": [{"Field": "_score", "IsDescending": "true"}], "GeoPolygonFilters": [], "TermFacetFilters": [], "FieldFilters": [], "GeoDistanceFacetFilters": [], "ScriptFilters": [], "Ids": ["88ecfe4b-7798-e311-aa29-00155d28de35"], "SelectedNumericFacets": null, "RelationCounts": [], "Options": null, "SelectedTermFacets": null, "DateTimeFacetFilters": [], "TermFacetSize": 1, "SelectedGeoFacets": null, "Query": "*", "Size": 1}
connectionpool.py          176 INFO     Starting new HTTP connection (1): localhost
connectionpool.py          344 DEBUG    "POST /xre2113qa.nightly/api/search/annotation HTTP/1.1" 200 2140
requests_api.py            140 INFO     Response recieved...
requests_api.py            141 INFO     Response status: 200
requests_api.py            142 INFO     Response reason: OK
requests_api.py            143 INFO     Response time: 0:00:02.443000
IncrementalUpdateAssertMixin.py  160 DEBUG    Search Result for Id - 88ecfe4b-7798-e311-aa29-00155d28de35 -:
IncrementalUpdateAssertMixin.py  161 DEBUG    {"versionnumber": 2080944, "annotationid": "88ecfe4b-7798-e311-aa29-00155d28de35", "subject": "TEST French / Fran\u00c3\u00a7ais"}
IncrementalUpdateAssertMixin.py   92 DEBUG    Entity with id - 88ecfe4b-7798-e311-aa29-00155d28de35 - exist in search: True
IncrementalUpdateAssertMixin.py   93 DEBUG    #######################
EntityBase.py              116 INFO     Sending PUT request..
EntityBase.py              272 DEBUG    Creating request body...
EntityBase.py              383 DEBUG    Request body created:
EntityBase.py              384 DEBUG    {"mimetype": "TEST Thai / \u00e0\u00b8\u00ab\u00e0\u00b8\u0099\u00e0\u00b9\u0089\u00e0\u00b8\u00b2\u00e0\u00b8\u00ab\u00e0\u00b8\u00a5\u00e0\u00b8\u00b1\u00e0\u00b8\u0081", "notetext": "TEST French / Fran\u00c3\u00a7ais", "subject": "TEST Russian / \u00d0\u00a0\u00d1\u0083\u00d1\u0081\u00d1\u0081\u00d0\u00ba\u00d0\u00b8\u00d0\u00b9", "type": "annotation", "filename": "TEST fzvmp"}
requests_api.py             76 INFO     Sending HTTP request...
requests_api.py             83 DEBUG    Method type: PUT
requests_api.py             94 DEBUG    Url: http://localhost/xre2113qa.nightly/api/note/88ecfe4b-7798-e311-aa29-00155d28de35/
requests_api.py             95 DEBUG    Headers: {'Authorization-Token': u'6569219054d540fb97925f7d0b93ffb3', 'Accept-Language': 'en-US,en;q=0.8', 'Content-Type': 'application/json', 'Accept-Encoding': 'deflate, gzip'}
requests_api.py            112 DEBUG    Request body: {"mimetype": "TEST Thai / \u00e0\u00b8\u00ab\u00e0\u00b8\u0099\u00e0\u00b9\u0089\u00e0\u00b8\u00b2\u00e0\u00b8\u00ab\u00e0\u00b8\u00a5\u00e0\u00b8\u00b1\u00e0\u00b8\u0081", "notetext": "TEST French / Fran\u00c3\u00a7ais", "subject": "TEST Russian / \u00d0\u00a0\u00d1\u0083\u00d1\u0081\u00d1\u0081\u00d0\u00ba\u00d0\u00b8\u00d0\u00b9", "type": "annotation", "filename": "TEST fzvmp"}
connectionpool.py          176 INFO     Starting new HTTP connection (1): localhost
connectionpool.py          344 DEBUG    "PUT /xre2113qa.nightly/api/note/88ecfe4b-7798-e311-aa29-00155d28de35/ HTTP/1.1" 200 1269
requests_api.py            140 INFO     Response recieved...
requests_api.py            141 INFO     Response status: 200
requests_api.py            142 INFO     Response reason: OK
requests_api.py            143 INFO     Response time: 0:00:03.115000
requests_api.py             76 INFO     Sending HTTP request...
requests_api.py             83 DEBUG    Method type: POST
requests_api.py             94 DEBUG    Url: http://localhost/xre2113qa.nightly/api/search/annotation
requests_api.py             95 DEBUG    Headers: {'Authorization-Token': u'6569219054d540fb97925f7d0b93ffb3', 'Accept-Language': 'en-US,en;q=0.8', 'Content-Type': 'application/json', 'Accept-Encoding': 'deflate, gzip'}
requests_api.py            104 DEBUG    Request body: {"ResultsFormat": null, "From": 0, "SelectedDateTimeFacets": null, "Relations": [], "PinTo": {"lat": -27.47018, "lon": 153.02911}, "NumericFacetFilters": [], "OrderBy": [{"Field": "_score", "IsDescending": "true"}], "GeoPolygonFilters": [], "TermFacetFilters": [], "FieldFilters": [], "GeoDistanceFacetFilters": [], "ScriptFilters": [], "Ids": ["88ecfe4b-7798-e311-aa29-00155d28de35"], "SelectedNumericFacets": null, "RelationCounts": [], "Options": null, "SelectedTermFacets": null, "DateTimeFacetFilters": [], "TermFacetSize": 1, "SelectedGeoFacets": null, "Query": "*", "Size": 1}
connectionpool.py          176 INFO     Starting new HTTP connection (1): localhost
connectionpool.py          344 DEBUG    "POST /xre2113qa.nightly/api/search/annotation HTTP/1.1" 200 2140
requests_api.py            140 INFO     Response recieved...
requests_api.py            141 INFO     Response status: 200
requests_api.py            142 INFO     Response reason: OK
requests_api.py            143 INFO     Response time: 0:00:00.835000
IncrementalUpdateAssertMixin.py  136 ERROR    Unable to get entity Index Version from index. entity-type=annotation|entity_id=88ecfe4b-7798-e311-aa29-00155d28de35 
IncrementalUpdateAssertMixin.py  138 ERROR    'IndexVersion'
Traceback (most recent call last):
  File "C:\EdgeDeployment\FunctionalTests\src\MEGS\Implementation\Assertions\IncrementalUpdateAssertMixin.py", line 132, in check_entity_index_version
    index_version = obj['Results'][0]['IndexVersion']
KeyError: 'IndexVersion'
connectionpool.py          296 DEBUG    "GET /xre2113qa.nightly/_search HTTP/1.1" 200 1076
#########################Server error trace#########################
{"index":[],"megs":[]}
